In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set visual aesthetic for notebook charts
sns.set_style("whitegrid")

# 1. Load all 5 datasets
beneficiaries = pd.read_csv('CFK2_Beneficiaries.csv')
health_visits = pd.read_csv('CFK2_HealthVisits.csv')
activities    = pd.read_csv('CFK2_ProgramActivities.csv')
loans         = pd.read_csv('CFK2_SACCOLoans.csv')
budgets       = pd.read_csv('CFK2_ProjectBudgets.csv')

# 2. Print summary of loaded records
print(" ALL DATASETS LOADED SUCCESSFULLY!\n")
print(f"• Beneficiaries:    {len(beneficiaries)} records")
print(f"• Health Visits:    {len(health_visits)} records")
print(f"• Program Activities:{len(activities)} records")
print(f"• SACCO Loans:      {len(loans)} records")
print(f"• Project Budgets:  {len(budgets)} records")

 ALL DATASETS LOADED SUCCESSFULLY!

• Beneficiaries:    120 records
• Health Visits:    202 records
• Program Activities:180 records
• SACCO Loans:      150 records
• Project Budgets:  100 records

In [7]:
# Inspect the first 5 rows of the beneficiaries dataset
print("=== BENEFICIARIES OVERVIEW ===")
display(beneficiaries.head())

# Check data types and missing values
print("\n=== BENEFICIARIES DATA INFO ===")
beneficiaries.info()

=== BENEFICIARIES OVERVIEW ===

,BeneficiaryID,FullName,Gender,Age,Village,RegistrationDate,Phone,ProgramArea,Status,EmergencyContact
0,CFK001,Amina Peter,Male,19.0,Gatwekera,2021/06/28,0764133326,Sports,inactive,0787 127 824
1,CFK002,Carol Fatuma,m,26.0,Soweto East,23-11-2021,0753 391 369,TechCraft,active,NaN
2,CFK003,Mwangi Daniel,FEMALE,13.0,LAINI SABA,2023-02-15,0780-407419,health outreach,Active,0715 793 384
3,CFK004,Esther Samuel,Female,15.0,gatwekera,18/01/2023,0757 472 528,Health Outreach,Suspended,0792 174 870
4,CFK005,Odhiambo Maina,F,24.0,Mashimoni,March 26 2022,0717340174,girls empowerment,Active,0737-694731

=== BENEFICIARIES DATA INFO ===
<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   BeneficiaryID     120 non-null    str
 1   FullName          120 non-null    str
 2   Gender            112 non-null    str
 3   Age               110 non-null    float64
 4   Village           113 non-null    str
 5   RegistrationDate  120 non-null    str
 6   Phone             84 non-null     str
 7   ProgramArea       114 non-null    str
 8   Status            120 non-null    str
 9   EmergencyContact  83 non-null     str
dtypes: float64(1), str(9)
memory usage: 9.5 KB

In [24]:
print("HEALTH VISITS OVERVIEW")
display(health_visits.head())

print("HEALTH VISITS OVERVIEW INFO")
health_visits.info()

HEALTH VISITS OVERVIEW

,VisitID,BeneficiaryID,VisitDate,Service,Diagnosis,Staff,ConsultationFee_KES,MedicationCost_KES,TotalBill_KES,InsuranceCovered,FollowUpRequired,Notes
0,V001,CFK000,11-06-2023,Nutrition,TYPHOID,Nurse Akinyi,1000,500,1500,YES,1,Referred to hospital
1,V002,CFK108,11-02-2024,Nutrition,Upper Respiratory Infection,Nurse Akinyi,1000,1200,2200,Y,False,Brought by parent
2,V003,CFK043,16-06-2023,Vaccination,NaN,nurse Wanjiru,1000,1200,2200,0,No,NaN
3,V004,CFK120,2023-09-12,Vaccination,malaria,Nurse Akinyi,1000,500,1500,True,N,First visit
4,V005,CFK099,2023-11-15,Vaccination,Diarrhea,NURSE WANJIRU,750,800,1550,0,N,Brought by parent

HEALTH VISITS OVERVIEW INFO
<class 'pandas.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   VisitID              202 non-null    str
 1   BeneficiaryID        202 non-null    str
 2   VisitDate            202 non-null    str
 3   Service              202 non-null    str
 4   Diagnosis            184 non-null    str
 5   Staff                202 non-null    str
 6   ConsultationFee_KES  200 non-null    str
 7   MedicationCost_KES   200 non-null    str
 8   TotalBill_KES        199 non-null    str
 9   InsuranceCovered     190 non-null    str
 10  FollowUpRequired     184 non-null    str
 11  Notes                143 non-null    str
dtypes: str(12)
memory usage: 19.1 KB

In [27]:
print("ACTIVITIES OVERVIEW ")
display(activities.head())

print("ACTIVITIES OVERVIEW INFO")
activities.info()

ACTIVITIES OVERVIEW

,ActivityID,BeneficiaryID,Program,ActivityName,ActivityDate,Attendance,ScoreGrade,CompletionStatus,Facilitator,SessionDuration_hrs,VenueCost_KES
0,A001,CFK099,girls empowerment,ICT Module 2,2023-06-15,absent,F,Completed,ms. nafula,1.5,500
1,A002,CFK063,Sports,Literacy Class,17/03/2024,Absent,Fail,NaN,ms. nafula,1.0,500
2,A003,CFK999,SPORTS,ICT Module 2,June 05 2023,Present,NaN,dropped out,coach otieno,1.5,0
3,A004,CFK100,Education,Football Training,January 03 2024,absent,Pass,Incomplete,MR. WEKESA,1.0,1000
4,A005,CFK006,SPORTS,ICT Module 1,03-11-2023,Absent,A-,dropped out,NaN,1.0,2000

ACTIVITIES OVERVIEW INFO
<class 'pandas.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ActivityID           180 non-null    str
 1   BeneficiaryID        180 non-null    str
 2   Program              180 non-null    str
 3   ActivityName         180 non-null    str
 4   ActivityDate         180 non-null    str
 5   Attendance           171 non-null    str
 6   ScoreGrade           121 non-null    str
 7   CompletionStatus     172 non-null    str
 8   Facilitator          163 non-null    str
 9   SessionDuration_hrs  152 non-null    float64
 10  VenueCost_KES        180 non-null    str
dtypes: float64(1), str(10)
memory usage: 15.6 KB

In [26]:
print("LOANS OVERVIEW")
display(loans.head())

print("LOANS OVERVIEW INFO")
loans.info()

LOANS OVERVIEW

,LoanID,BeneficiaryID,ApplicationDate,LoanAmount_KES,InterestRate_pct,RepaymentPeriod_months,MonthlyInstalment_KES,Purpose,Status,OfficerName,DisbursementDate,TotalRepaid_KES,OutstandingBalance_KES
0,L001,CFK074,May 18 2023,100000,NaN,24.0,4667,Housing,Defaulted,MR. OTIENO,20/07/2023,86850,13150
1,L002,CFK084,17-06-2022,75000,14.0,6.0,14000,Food,Defaulted,MR. OTIENO,2023/11/05,18775,56225
2,L003,CFK000,2022-09-11,25000,14.0,NaN,2333,Food,Defaulted,Mr. Otieno,22/01/2023,20977,4023
3,L004,CFK106,2023-05-17,100000,NaN,NaN,9333,business,rejected,Ms Chebet,2024/01/30,79621,20379
4,L005,CFK092,09/06/2022,15000,14.0,NaN,1400,Housing,rejected,Ms. Chebet,March 26 2023,11885,3115

LOANS OVERVIEW INFO
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   LoanID                  150 non-null    str
 1   BeneficiaryID           150 non-null    str
 2   ApplicationDate         150 non-null    str
 3   LoanAmount_KES          150 non-null    str
 4   InterestRate_pct        114 non-null    float64
 5   RepaymentPeriod_months  124 non-null    float64
 6   MonthlyInstalment_KES   148 non-null    str
 7   Purpose                 139 non-null    str
 8   Status                  140 non-null    str
 9   OfficerName             150 non-null    str
 10  DisbursementDate        143 non-null    str
 11  TotalRepaid_KES         149 non-null    str
 12  OutstandingBalance_KES  144 non-null    str
dtypes: float64(2), str(11)
memory usage: 15.4 KB

In [29]:
print("BUDGETS OVERVIEW")
display(budgets.head())

print("BUDGETS OVERVIEW INFO")
budgets.info()

BUDGETS OVERVIEW

,BudgetID,ProjectName,Donor,FiscalYear,BudgetLine,AllocatedBudget_KES,ActualSpend_KES,VarianceExplained,ApprovedBy,ReportingDate,BudgetUtilisation_pct,AuditStatus
0,B001,WASH Assessment,Wellcome Trust,2023,Equipment,750000,826081,Overspend approved by board,Finance Director,November 09 2022,110.1,NaN
1,B002,Health Outreach Q1,usaid,2024,Food & Nutrition,1000000,1054032,On track,Board Chair,27-09-2022,105.4,PENDING
2,B003,CDC Surveillance Q2,Wellcome Trust,FY2024,Personnel,250000,133987,NaN,Board chair,November 09 2023,53.6,NaN
3,B004,Youth Economic Dev,local government,2022/23,Monitoring & Evaluation,2000000 KES,1138884 KES,Donor approved reallocation,ED Kamau,04-02-2023,56.9,pending
4,B005,CDC Surveillance Q2,UN Women,NaN,Training Materials,800000,469828,Exchange rate fluctuation,FINANCE DIRECTOR,2022/07/24,58.7,verified

BUDGETS OVERVIEW INFO
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   BudgetID               100 non-null    str
 1   ProjectName            100 non-null    str
 2   Donor                  89 non-null     str
 3   FiscalYear             78 non-null     str
 4   BudgetLine             100 non-null    str
 5   AllocatedBudget_KES    99 non-null     str
 6   ActualSpend_KES        98 non-null     str
 7   VarianceExplained      75 non-null     str
 8   ApprovedBy             93 non-null     str
 9   ReportingDate          91 non-null     str
 10  BudgetUtilisation_pct  97 non-null     str
 11  AuditStatus            80 non-null     str
dtypes: str(12)
memory usage: 9.5 KB

In [22]:
import pandas as pd
import numpy as np

# 1. LOAD ALL 5 DATASETS
beneficiaries = pd.read_csv('CFK2_Beneficiaries.csv')
health_visits = pd.read_csv('CFK2_HealthVisits.csv')
activities    = pd.read_csv('CFK2_ProgramActivities.csv')
loans         = pd.read_csv('CFK2_SACCOLoans.csv')
budgets       = pd.read_csv('CFK2_ProjectBudgets.csv')


# ==========================================
# 2. HELPER FUNCTIONS
# ==========================================
def clean_text(df, columns):
    for col in columns:
        if col in df.columns:
            df[col] = df[col].str.replace('&nbsp;', ' ', regex=True).str.strip().str.title()
    return df

def clean_currency_col(val):
    if pd.isna(val):
        return np.nan
    if isinstance(val, str):
        val = val.replace('KES', '').replace(',', '').strip()
    try:
        return float(val)
    except:
        return np.nan

def clean_phone_col(val):
    if pd.isna(val):
        return np.nan
    return str(val).replace(' ', '').replace('-', '').strip()

def clean_fiscal_year(val):
    if pd.isna(val):
        return np.nan
    val = str(val).strip().upper()
    val = val.replace('FY', '')
    return val


# ==========================================
# 3. CLEANING BENEFICIARIES DATASET
# ==========================================
gender_map = {'m': 'Male', 'M': 'Male', 'male': 'Male', 'Male': 'Male',
              'f': 'Female', 'F': 'Female', 'female': 'Female', 'FEMALE': 'Female'}
beneficiaries['Gender'] = beneficiaries['Gender'].map(gender_map)
beneficiaries = clean_text(beneficiaries, ['Village', 'ProgramArea', 'Status'])
beneficiaries['RegistrationDate'] = pd.to_datetime(beneficiaries['RegistrationDate'], errors='coerce', format='mixed')

beneficiaries['Phone'] = beneficiaries['Phone'].apply(clean_phone_col)
beneficiaries['EmergencyContact'] = beneficiaries['EmergencyContact'].apply(clean_phone_col)


# ==========================================
# 4. CLEANING HEALTH VISITS DATASET
# ==========================================
health_visits = clean_text(health_visits, ['Service', 'Staff', 'Notes'])
health_visits['Diagnosis'] = health_visits['Diagnosis'].str.strip().str.upper()
health_visits['VisitDate'] = pd.to_datetime(health_visits['VisitDate'], errors='coerce', format='mixed')

for col in ['ConsultationFee_KES', 'MedicationCost_KES', 'TotalBill_KES']:
    health_visits[col] = health_visits[col].apply(clean_currency_col).fillna(0)

bool_map = {
    'YES': True, 'Yes': True, 'yes': True, 'Y': True, 'True': True, '1': True, 1: True,
    'NO': False, 'No': False, 'no': False, 'N': False, 'False': False, '0': False, 0: False
}
health_visits['InsuranceCovered'] = health_visits['InsuranceCovered'].map(bool_map)
health_visits['FollowUpRequired'] = health_visits['FollowUpRequired'].map(bool_map)


# ==========================================
# 5. CLEANING PROGRAM ACTIVITIES DATASET
# ==========================================
activities = clean_text(activities, ['Program', 'ActivityName', 'Attendance', 'CompletionStatus', 'Facilitator'])
activities['ActivityDate'] = pd.to_datetime(activities['ActivityDate'], errors='coerce', format='mixed')
activities['VenueCost_KES'] = activities['VenueCost_KES'].apply(clean_currency_col).fillna(0)

score_map = {
    'A': 'A', 'A-': 'A-', 'B+': 'B+', 'B': 'B', 'C+': 'C+', 'C': 'C',
    'F': 'F', 'Fail': 'F', 'Pass': 'Pass'
}
activities['ScoreGrade'] = activities['ScoreGrade'].map(score_map)
attendance_map = {
    'Present': 'Present', 'present': 'Present', 'PRESENT': 'Present', 'Present ': 'Present', '1': 'Present', 1: 'Present',
    'Absent': 'Absent', 'absent': 'Absent', 'ABSENT': 'Absent', '0': 'Absent', 0: 'Absent'
}

activities['Attendance'] = activities['Attendance'].map(attendance_map)


# ==========================================
# 6. CLEANING SACCO LOANS DATASET
# ==========================================
loans = clean_text(loans, ['Purpose', 'Status', 'OfficerName'])
loans['ApplicationDate'] = pd.to_datetime(loans['ApplicationDate'], errors='coerce', format='mixed')
loans['DisbursementDate'] = pd.to_datetime(loans['DisbursementDate'], errors='coerce', format='mixed')

for col in ['LoanAmount_KES', 'MonthlyInstalment_KES', 'TotalRepaid_KES', 'OutstandingBalance_KES']:
    loans[col] = loans[col].apply(clean_currency_col)


# ==========================================
# 7. CLEANING PROJECT BUDGETS DATASET
# ==========================================
budgets = clean_text(budgets, ['ProjectName', 'BudgetLine', 'VarianceExplained', 'ApprovedBy', 'AuditStatus'])
budgets['Donor'] = budgets['Donor'].str.strip().str.upper()
budgets['ReportingDate'] = pd.to_datetime(budgets['ReportingDate'], errors='coerce', format='mixed')

budgets['AllocatedBudget_KES'] = budgets['AllocatedBudget_KES'].apply(clean_currency_col)
budgets['ActualSpend_KES'] = budgets['ActualSpend_KES'].apply(clean_currency_col)
budgets['BudgetUtilisation_pct'] = pd.to_numeric(budgets['BudgetUtilisation_pct'], errors='coerce')
budgets['FiscalYear'] = budgets['FiscalYear'].apply(clean_fiscal_year)


# ==========================================
# 8. ADD RECORD STATUS FLAG (LOOP)
# ==========================================
registered_ids = set(beneficiaries['BeneficiaryID'])
operational_tables = {
    'Health Visits': health_visits,
    'Program Activities': activities,
    'SACCO Loans': loans
}

for name, df in operational_tables.items():
    df['RecordStatus'] = df['BeneficiaryID'].apply(
        lambda x: 'Registered Member' if x in registered_ids else 'Unregistered / Walk-in'
    )



print(" ALL DATASETS CLEANED, FLAGGED, AND SAVED SUCCESSFULLY!")

 ALL DATASETS CLEANED, FLAGGED, AND SAVED SUCCESSFULLY!

In [14]:
beneficiaries.head()

,BeneficiaryID,FullName,Gender,Age,Village,RegistrationDate,Phone,ProgramArea,Status,EmergencyContact
0,CFK001,Amina Peter,Male,19.0,Gatwekera,2021-06-28,0764133326,Sports,Inactive,0787127824
1,CFK002,Carol Fatuma,Male,26.0,Soweto East,2021-11-23,0753391369,Techcraft,Active,NaN
2,CFK003,Mwangi Daniel,Female,13.0,Laini Saba,2023-02-15,0780407419,Health Outreach,Active,0715793384
3,CFK004,Esther Samuel,NaN,15.0,Gatwekera,2023-01-18,0757472528,Health Outreach,Suspended,0792174870
4,CFK005,Odhiambo Maina,Female,24.0,Mashimoni,2022-03-26,0717340174,Girls Empowerment,Active,0737694731

In [23]:
activities.head()

,ActivityID,BeneficiaryID,Program,ActivityName,ActivityDate,Attendance,ScoreGrade,CompletionStatus,Facilitator,SessionDuration_hrs,VenueCost_KES,RecordStatus
0,A001,CFK099,Girls Empowerment,Ict Module 2,2023-06-15,Absent,F,Completed,Ms. Nafula,1.5,500.0,Registered Member
1,A002,CFK063,Sports,Literacy Class,2024-03-17,Absent,F,NaN,Ms. Nafula,1.0,500.0,Registered Member
2,A003,CFK999,Sports,Ict Module 2,2023-06-05,Present,NaN,Dropped Out,Coach Otieno,1.5,0.0,Unregistered / Walk-in
3,A004,CFK100,Education,Football Training,2024-01-03,Absent,Pass,Incomplete,Mr. Wekesa,1.0,1000.0,Registered Member
4,A005,CFK006,Sports,Ict Module 1,2023-03-11,Absent,A-,Dropped Out,NaN,1.0,2000.0,Registered Member

In [24]:
loans.head()

,LoanID,BeneficiaryID,ApplicationDate,LoanAmount_KES,InterestRate_pct,RepaymentPeriod_months,MonthlyInstalment_KES,Purpose,Status,OfficerName,DisbursementDate,TotalRepaid_KES,OutstandingBalance_KES,RecordStatus
0,L001,CFK074,2023-05-18,100000.0,NaN,24.0,4667.0,Housing,Defaulted,Mr. Otieno,2023-07-20,86850.0,13150.0,Registered Member
1,L002,CFK084,2022-06-17,75000.0,14.0,6.0,14000.0,Food,Defaulted,Mr. Otieno,2023-11-05,18775.0,56225.0,Registered Member
2,L003,CFK000,2022-09-11,25000.0,14.0,NaN,2333.0,Food,Defaulted,Mr. Otieno,2023-01-22,20977.0,4023.0,Unregistered / Walk-in
3,L004,CFK106,2023-05-17,100000.0,NaN,NaN,9333.0,Business,Rejected,Ms Chebet,2024-01-30,79621.0,20379.0,Registered Member
4,L005,CFK092,2022-09-06,15000.0,14.0,NaN,1400.0,Housing,Rejected,Ms. Chebet,2023-03-26,11885.0,3115.0,Registered Member

In [25]:
budgets.head()

,BudgetID,ProjectName,Donor,FiscalYear,BudgetLine,AllocatedBudget_KES,ActualSpend_KES,VarianceExplained,ApprovedBy,ReportingDate,BudgetUtilisation_pct,AuditStatus
0,B001,Wash Assessment,WELLCOME TRUST,2023,Equipment,750000.0,826081.0,Overspend Approved By Board,Finance Director,2022-11-09,110.1,NaN
1,B002,Health Outreach Q1,USAID,2024,Food & Nutrition,1000000.0,1054032.0,On Track,Board Chair,2022-09-27,105.4,Pending
2,B003,Cdc Surveillance Q2,WELLCOME TRUST,2024,Personnel,250000.0,133987.0,NaN,Board Chair,2023-11-09,53.6,NaN
3,B004,Youth Economic Dev,LOCAL GOVERNMENT,2022/23,Monitoring & Evaluation,2000000.0,1138884.0,Donor Approved Reallocation,Ed Kamau,2023-04-02,56.9,Pending
4,B005,Cdc Surveillance Q2,UN WOMEN,NaN,Training Materials,800000.0,469828.0,Exchange Rate Fluctuation,Finance Director,2022-07-24,58.7,Verified

In [26]:
health_visits.head()

,VisitID,BeneficiaryID,VisitDate,Service,Diagnosis,Staff,ConsultationFee_KES,MedicationCost_KES,TotalBill_KES,InsuranceCovered,FollowUpRequired,Notes,RecordStatus
0,V001,CFK000,2023-11-06,Nutrition,TYPHOID,Nurse Akinyi,1000.0,500.0,1500.0,True,True,Referred To Hospital,Unregistered / Walk-in
1,V002,CFK108,2024-11-02,Nutrition,UPPER RESPIRATORY INFECTION,Nurse Akinyi,1000.0,1200.0,2200.0,True,False,Brought By Parent,Registered Member
2,V003,CFK043,2023-06-16,Vaccination,NaN,Nurse Wanjiru,1000.0,1200.0,2200.0,False,False,NaN,Registered Member
3,V004,CFK120,2023-09-12,Vaccination,MALARIA,Nurse Akinyi,1000.0,500.0,1500.0,True,False,First Visit,Registered Member
4,V005,CFK099,2023-11-15,Vaccination,DIARRHEA,Nurse Wanjiru,750.0,800.0,1550.0,False,False,Brought By Parent,Registered Member

In [33]:
loans.tail(10)

,LoanID,BeneficiaryID,ApplicationDate,LoanAmount_KES,InterestRate_pct,RepaymentPeriod_months,MonthlyInstalment_KES,Purpose,Status,OfficerName,DisbursementDate,TotalRepaid_KES,OutstandingBalance_KES,RecordStatus
140,L141,CFK048,2024-11-01,15000.0,15.0,24.0,700.0,Food,Defaulted,Ms. Chebet,2022-05-09,4800.0,NaN,Registered Member
141,L142,CFK021,2022-08-09,10000.0,12.0,6.0,1867.0,School Fees,Active,Ms Chebet,2023-09-14,7703.0,2297.0,Registered Member
142,L143,CFK093,2024-02-27,30000.0,14.0,18.0,1867.0,Food,Pending,Mr. Hassan,2023-02-27,4065.0,25935.0,Registered Member
143,L144,CFK059,2023-12-28,20000.0,12.5,18.0,1244.0,NaN,Rejected,Mr. Hassan,2022-01-27,14757.0,5243.0,Registered Member
144,L145,CFK040,2023-02-05,25000.0,15.0,18.0,1556.0,NaN,Defaulted,Ms. Chebet,2023-08-22,9579.0,15421.0,Registered Member
145,L146,CFK022,2022-12-19,100000.0,NaN,6.0,18667.0,Medical,NaN,Mr. Otieno,2022-12-17,63602.0,36398.0,Registered Member
146,L147,CFK046,2023-05-26,5000.0,10.0,24.0,233.0,Business,Approved,Mr. Otieno,2024-05-16,269.0,4731.0,Registered Member
147,L148,CFK095,2022-07-07,20000.0,15.0,NaN,1867.0,School Fees,Rejected,Mr. Otieno,2022-01-08,2993.0,17007.0,Registered Member
148,L149,CFK102,2023-10-12,20000.0,15.0,12.0,1867.0,Medical,Approved,Ms Chebet,2022-04-25,3272.0,16728.0,Registered Member
149,L150,CFK998,2023-09-08,75000.0,15.0,18.0,4667.0,Business,Active,Mr Hassan,2023-03-27,39274.0,35726.0,Unregistered / Walk-in

In [18]:
# Find rows in health visits where the BeneficiaryID is NOT in the beneficiaries table
unregistered_visits = health_visits[~health_visits['BeneficiaryID'].isin(beneficiaries['BeneficiaryID'])]

print(f"Number of visits from unregistered beneficiaries: {len(unregistered_visits)}")
display(unregistered_visits.head())

Number of visits from unregistered beneficiaries: 16

,VisitID,BeneficiaryID,VisitDate,Service,Diagnosis,Staff,ConsultationFee_KES,MedicationCost_KES,TotalBill_KES,InsuranceCovered,FollowUpRequired,Notes
0,V001,CFK000,2023-11-06,Nutrition,TYPHOID,Nurse Akinyi,1000.0,500.0,1500.0,True,True,Referred To Hospital
21,V022,CFK030,2023-12-31,Reproductive Health,MALARIA,Dr. Mutua,200.0,800.0,1000.0,True,True,Follow Up From Last Month
27,V028,CFK998,2023-03-29,Wash Screening,DIARRHEA,Dr. Mutua,500.0,1200.0,1700.0,False,True,Follow Up From Last Month
55,V056,CFK998,2024-04-08,Vaccination,NORMAL,Nurse Wanjiru,750.0,0.0,0.0,True,False,First Visit
67,V068,CFK015,2023-12-11,Nutrition,TYPHOID,Nurse Akinyi,500.0,2000.0,2500.0,False,NaN,Brought By Parent